# Generated by Django 3.1.7 on 2021-04-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
