# Generated by Django 3.1.7 on 2021-04-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20210415_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
